import { describe, it, expect } from 'vitest';
import { verify } from 'node:crypto';
import {
  buildAuthHeaders,
  buildSignatureMessage,
  privateKeyFromBase64Seed,
  publicKeyBase64,
  publicKeyFromBase64,
  currentTimestampSeconds,
  InvalidPrivateKeyError,
} from '../src/shared/signer.js';

/**
 * Key material published in Robinhood's own API documentation as an example.
 * These are documentation values, not live credentials.
 */
const DOC_PRIVATE_KEY = 'xQnTJVeQLmw1/Mg2YimEViSpw/SdJcgNXZ5kQkAXNPU=';
const DOC_PUBLIC_KEY = 'jPItx4TLjcnSUnmnXQQyAKL4eJj3+oWNNMmmm2vATqk=';
const DOC_API_KEY = 'rh-api-6148effc-c0b1-486c-8940-a1d099456be6';
const DOC_TIMESTAMP = 1698708981;
const DOC_PATH = '/api/v1/crypto/trading/orders/';
const DOC_SIGNATURE =
  'q/nEtxp/P2Or3hph3KejBqnw5o9qeuQ+hYRnB56FaHbjDsNUY9KhB1asMxohDnzdVFSD7StaTqjSd9U9HvaRAw==';

describe('key handling', () => {
  it('derives the public key Robinhood documents for its example private key', () => {
    // The strongest available check that seed handling is correct: Robinhood
    // publishes both halves, and only correct PKCS#8 wrapping reproduces one
    // from the other.
    const privateKey = privateKeyFromBase64Seed(DOC_PRIVATE_KEY);
    expect(publicKeyBase64(privateKey)).toBe(DOC_PUBLIC_KEY);
  });

  it('rejects a 64-byte expanded keypair with a message naming the mistake', () => {
    const expanded = Buffer.concat([
      Buffer.from(DOC_PRIVATE_KEY, 'base64'),
      Buffer.from(DOC_PUBLIC_KEY, 'base64'),
    ]).toString('base64');

    expect(() => privateKeyFromBase64Seed(expanded)).toThrow(InvalidPrivateKeyError);
    expect(() => privateKeyFromBase64Seed(expanded)).toThrow(/64-byte keypair/);
  });

  it('rejects a key of the wrong length', () => {
    expect(() => privateKeyFromBase64Seed(Buffer.alloc(16).toString('base64'))).toThrow(
      /must decode to 32 bytes, got 16/,
    );
  });

  it('tolerates surrounding whitespace, which shells and .env files add', () => {
    const privateKey = privateKeyFromBase64Seed(`  ${DOC_PRIVATE_KEY}\n`);
    expect(publicKeyBase64(privateKey)).toBe(DOC_PUBLIC_KEY);
  });
});

describe('signature message', () => {
  it('concatenates api key, timestamp, path, method, body with no separators', () => {
    expect(
      buildSignatureMessage({
        apiKey: 'KEY',
        timestamp: 123,
        path: '/api/v1/x/',
        method: 'POST',
        body: '{"a":1}',
      }),
    ).toBe('KEY123/api/v1/x/POST{"a":1}');
  });

  it('omits the body for requests that have none', () => {
    expect(
      buildSignatureMessage({ apiKey: 'KEY', timestamp: 1, path: '/p/', method: 'GET' }),
    ).toBe('KEY1/p/GET');
  });

  it('uppercases the method', () => {
    expect(
      buildSignatureMessage({ apiKey: 'K', timestamp: 1, path: '/p/', method: 'post' }),
    ).toBe('K1/p/POST');
  });
});

describe('buildAuthHeaders', () => {
  it('produces a signature that verifies against the matching public key', () => {
    const privateKey = privateKeyFromBase64Seed(DOC_PRIVATE_KEY);
    const body = '{"symbol":"BTC-USD"}';

    const headers = buildAuthHeaders({
      apiKey: DOC_API_KEY,
      privateKey,
      path: DOC_PATH,
      method: 'POST',
      body,
      timestamp: DOC_TIMESTAMP,
    });

    const message = buildSignatureMessage({
      apiKey: DOC_API_KEY,
      timestamp: DOC_TIMESTAMP,
      path: DOC_PATH,
      method: 'POST',
      body,
    });

    const verified = verify(
      null,
      Buffer.from(message, 'utf8'),
      publicKeyFromBase64(DOC_PUBLIC_KEY),
      Buffer.from(headers['x-signature'], 'base64'),
    );

    expect(verified).toBe(true);
    expect(headers['x-api-key']).toBe(DOC_API_KEY);
    expect(headers['x-timestamp']).toBe(String(DOC_TIMESTAMP));
  });

  it('emits the timestamp in seconds, not milliseconds', () => {
    const headers = buildAuthHeaders({
      apiKey: 'K',
      privateKey: privateKeyFromBase64Seed(DOC_PRIVATE_KEY),
      path: '/p/',
      method: 'GET',
    });

    const timestamp = Number(headers['x-timestamp']);
    // A ms timestamp would be ~1e12; seconds are ~1e9. Robinhood rejects
    // anything more than 30s stale, so this unit error is fatal in production.
    expect(timestamp).toBeLessThan(1e11);
    expect(Math.abs(timestamp - currentTimestampSeconds())).toBeLessThanOrEqual(2);
  });
});

describe("Robinhood's published conformance vector", () => {
  /**
   * Robinhood documents a worked example and invites implementers to check
   * their signature against it. That published signature does NOT correspond
   * to the JSON body a real client sends: it was generated by signing a Python
   * dict repr (single quotes, spaces after colons, and a different key order
   * than the accompanying table shows).
   *
   * This is pinned as a test so the quirk stays documented and nobody "fixes"
   * a correct implementation to chase it. Signing the JSON body: what every
   * working client does, and what Robinhood's own sample code does at runtime , 
   * is correct.
   */
  const DICT_REPR_BODY =
    "{'client_order_id': '131de903-5a9c-4260-abc1-28d562a5dcf0', 'side': 'buy', " +
    "'symbol': 'BTC-USD', 'type': 'market', 'market_order_config': {'asset_quantity': '0.1'}}";

  const JSON_BODY =
    '{"client_order_id":"131de903-5a9c-4260-abc1-28d562a5dcf0","side":"buy",' +
    '"type":"market","symbol":"BTC-USD","market_order_config":{"asset_quantity":"0.1"}}';

  const verifyVector = (body: string) =>
    verify(
      null,
      Buffer.from(
        buildSignatureMessage({
          apiKey: DOC_API_KEY,
          timestamp: DOC_TIMESTAMP,
          path: DOC_PATH,
          method: 'POST',
          body,
        }),
        'utf8',
      ),
      publicKeyFromBase64(DOC_PUBLIC_KEY),
      Buffer.from(DOC_SIGNATURE, 'base64'),
    );

  it('matches only a Python dict repr, confirming the published vector is unusable', () => {
    expect(verifyVector(DICT_REPR_BODY)).toBe(true);
  });

  it('does not match the JSON body a real client sends over the wire', () => {
    expect(verifyVector(JSON_BODY)).toBe(false);
  });
});
